services:
  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - 'Inception'
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - '3306'
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
    networks:
      - 'Inception'
    depends_on:
      - 'wordpress'
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - 'Inception'
    depends_on:
      - 'mariadb'
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    expose:
      - '9000'
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/mariadb'

networks:
  Inception:
    driver: bridge
